import React, { useState } from 'react';
import { PortfolioTemplateId } from '../types';
import { Calculator, TrendingUp, DollarSign, ArrowRight, Sparkles, Check, Cloud, CheckCircle, HardDrive, ExternalLink, Loader2 } from 'lucide-react';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db, auth, getAccessToken, googleSignIn } from '../lib/firebase';
import { uploadDriveTextFile } from '../lib/googleDrive';

interface Props {
  currentTemplate: PortfolioTemplateId;
  onOpenBookingModal: () => void;
}

export const RoiCalculatorSection: React.FC<Props> = ({ currentTemplate, onOpenBookingModal }) => {
  const [monthlyVisitors, setMonthlyVisitors] = useState<number>(3500);
  const [conversionRate, setConversionRate] = useState<number>(2.0);
  const [averageOrderValue, setAverageOrderValue] = useState<number>(120);
  const [growthMultiplier, setGrowthMultiplier] = useState<number>(3.5); // 3.5x Traffic Growth
  const [isSaved, setIsSaved] = useState<boolean>(false);
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [isSavingToDrive, setIsSavingToDrive] = useState<boolean>(false);
  const [driveSavedMsg, setDriveSavedMsg] = useState<string | null>(null);
  const [driveSavedUrl, setDriveSavedUrl] = useState<string | null>(null);

  const isDark = currentTemplate === 'cyber';

  // Math calculations
  const baselineMonthlySales = (monthlyVisitors * (conversionRate / 100));
  const baselineMonthlyRevenue = baselineMonthlySales * averageOrderValue;

  const projectedVisitors = monthlyVisitors * growthMultiplier;
  const projectedConversionRate = Math.min(conversionRate * 1.3, 8.0); // CRO boost +30%
  const projectedMonthlySales = projectedVisitors * (projectedConversionRate / 100);
  const projectedMonthlyRevenue = projectedMonthlySales * averageOrderValue;

  const monthlyRevenueGain = projectedMonthlyRevenue - baselineMonthlyRevenue;
  const annualRevenueGain = monthlyRevenueGain * 12;

  const handleSaveScenario = async () => {
    setIsSaving(true);
    try {
      await addDoc(collection(db, 'roi_scenarios'), {
        monthlyTraffic: monthlyVisitors,
        conversionRate,
        averageOrderValue,
        projectedTrafficGrowth: growthMultiplier,
        calculatedMonthlyRevenue: Math.round(baselineMonthlyRevenue),
        calculatedProjectedRevenue: Math.round(projectedMonthlyRevenue),
        calculatedRevenueLift: Math.round(annualRevenueGain),
        userId: auth.currentUser?.uid || null,
        createdAt: serverTimestamp()
      });
      setIsSaved(true);
      setTimeout(() => setIsSaved(false), 3000);
    } catch (err) {
      console.warn("Could not save ROI scenario to Firestore:", err);
    } finally {
      setIsSaving(false);
    }
  };

  const handleExportScenarioToDrive = async () => {
    setIsSavingToDrive(true);
    setDriveSavedMsg(null);
    setDriveSavedUrl(null);
    try {
      let token = await getAccessToken();
      if (!token) {
        const authRes = await googleSignIn();
        if (!authRes) {
          setDriveSavedMsg('Google sign-in required to export to Drive.');
          setIsSavingToDrive(false);
          return;
        }
      }

      const fileName = `SEOWebFly_ROI_Projection_${Date.now()}.md`;
      const markdown = `# SEOWebFly Organic ROI Growth Projection
Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}

## Current Baseline Metrics
- Monthly Organic Visitors: ${monthlyVisitors.toLocaleString()}
- Current E-commerce Conversion Rate: ${conversionRate}%
- Average Order Value (AOV): $${averageOrderValue}
- Baseline Monthly Revenue: $${Math.round(baselineMonthlyRevenue).toLocaleString()}

## SEOWebFly Organic Expansion Targets
- Traffic Multiplier: ${growthMultiplier}x
- Projected Monthly Visitors: ${Math.round(projectedVisitors).toLocaleString()}
- Optimized Conversion Rate: ${projectedConversionRate.toFixed(1)}% (+30% CRO boost)
- Projected Monthly Revenue: $${Math.round(projectedMonthlyRevenue).toLocaleString()}

## Net Financial Impact
- **Monthly Revenue Expansion**: +$${Math.round(monthlyRevenueGain).toLocaleString()}
- **Annual Net Revenue Addition**: +$${Math.round(annualRevenueGain).toLocaleString()} / year

---
Generated by SEOWebFly Digital Growth Agency • https://seowebfly.com
`;

      const file = await uploadDriveTextFile(fileName, markdown, 'text/markdown');
      setDriveSavedMsg(`Scenario saved to Google Drive as "${file.name}"!`);
      if (file.webViewLink) {
        setDriveSavedUrl(file.webViewLink);
      }
    } catch (err: any) {
      console.error('Drive save error:', err);
      setDriveSavedMsg(err.message || 'Failed to export to Google Drive.');
    } finally {
      setIsSavingToDrive(false);
    }
  };

  return (
    <section id="roi-calc" className="py-20 transition-colors bg-[#0A0A0B] text-[#E2E8F0]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 space-y-12">
        
        {/* Title Header */}
        <div className="text-center max-w-3xl mx-auto space-y-3">
          <div className="inline-flex items-center gap-2 bg-[#12131A] text-teal-300 border border-teal-500/30 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            <Calculator className="w-3.5 h-3.5 text-amber-400" />
            <span>Interactive Organic Growth Estimator</span>
          </div>
          <h2 className="font-space font-extrabold text-3xl sm:text-4xl lg:text-5xl tracking-tight text-white">
            Calculate Your Organic Traffic & Revenue ROI
          </h2>
          <p className="text-sm sm:text-base text-slate-300">
            Adjust the sliders below to estimate your potential revenue expansion based on historical SEOWebFly campaign outcomes.
          </p>
        </div>

        {/* Calculator Main Container */}
        <div className="rounded-3xl p-6 sm:p-10 border shadow-2xl bg-[#12131A] border-[#1E202D]">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
            
            {/* Left Controls Sliders */}
            <div className="lg:col-span-7 space-y-6">
              
              {/* Slider 1: Monthly Visitors */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs sm:text-sm font-bold">
                  <span className="text-slate-200">Current Monthly Organic Visitors:</span>
                  <span className="font-space font-extrabold text-base text-[#70d7d1]">
                    {monthlyVisitors.toLocaleString()} visitors / mo
                  </span>
                </div>
                <input
                  type="range"
                  min="500"
                  max="50000"
                  step="500"
                  value={monthlyVisitors}
                  onChange={(e) => setMonthlyVisitors(Number(e.target.value))}
                  className="w-full h-2 bg-[#181a24] border border-[#222533] rounded-lg appearance-none cursor-pointer accent-[#34a29d]"
                />
                <div className="flex justify-between text-[10px] text-slate-400">
                  <span>500</span>
                  <span>25,000</span>
                  <span>50,000+</span>
                </div>
              </div>

              {/* Slider 2: Conversion Rate */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs sm:text-sm font-bold">
                  <span className="text-slate-200">Average E-commerce / Lead Conversion Rate (%):</span>
                  <span className="font-space font-extrabold text-base text-[#70d7d1]">
                    {conversionRate.toFixed(1)}%
                  </span>
                </div>
                <input
                  type="range"
                  min="0.5"
                  max="6.0"
                  step="0.1"
                  value={conversionRate}
                  onChange={(e) => setConversionRate(Number(e.target.value))}
                  className="w-full h-2 bg-[#181a24] border border-[#222533] rounded-lg appearance-none cursor-pointer accent-[#34a29d]"
                />
                <div className="flex justify-between text-[10px] text-slate-400">
                  <span>0.5%</span>
                  <span>3.0%</span>
                  <span>6.0%</span>
                </div>
              </div>

              {/* Slider 3: Average Order / Lead Value */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs sm:text-sm font-bold">
                  <span className="text-slate-200">Average Order / Customer Value ($):</span>
                  <span className="font-space font-extrabold text-base text-[#70d7d1]">
                    ${averageOrderValue.toLocaleString()}
                  </span>
                </div>
                <input
                  type="range"
                  min="20"
                  max="1000"
                  step="10"
                  value={averageOrderValue}
                  onChange={(e) => setAverageOrderValue(Number(e.target.value))}
                  className="w-full h-2 bg-[#181a24] border border-[#222533] rounded-lg appearance-none cursor-pointer accent-[#34a29d]"
                />
                <div className="flex justify-between text-[10px] text-slate-400">
                  <span>$20</span>
                  <span>$500</span>
                  <span>$1,000+</span>
                </div>
              </div>

              {/* Slider 4: Target Campaign Expansion */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs sm:text-sm font-bold">
                  <span className="text-slate-200">SEOWebFly Campaign Expansion Goal:</span>
                  <span className="font-space font-extrabold text-base text-emerald-400">
                    {growthMultiplier.toFixed(1)}x Traffic Scaling
                  </span>
                </div>
                <input
                  type="range"
                  min="1.5"
                  max="6.0"
                  step="0.5"
                  value={growthMultiplier}
                  onChange={(e) => setGrowthMultiplier(Number(e.target.value))}
                  className="w-full h-2 bg-[#181a24] border border-[#222533] rounded-lg appearance-none cursor-pointer accent-emerald-500"
                />
                <div className="flex justify-between text-[10px] text-slate-400">
                  <span>1.5x (Conservative)</span>
                  <span>3.5x (Avg 1Click Wallpapers)</span>
                  <span>6.0x (Aggressive)</span>
                </div>
              </div>

            </div>

            {/* Right Projection Output Card */}
            <div className="lg:col-span-5 bg-gradient-to-br from-[#006a66] to-[#004d49] text-white p-6 sm:p-8 rounded-3xl space-y-6 shadow-2xl border border-teal-500/30">
              
              <div className="flex items-center justify-between pb-3 border-b border-teal-500/40">
                <span className="text-xs font-bold uppercase tracking-wider text-teal-200">PROJECTED REVENUE EXPANSION</span>
                <Sparkles className="w-5 h-5 text-amber-300" />
              </div>

              {/* Big Revenue Number */}
              <div className="space-y-1">
                <div className="text-xs text-teal-200 font-medium">Estimated Annual Revenue Gain:</div>
                <div className="font-space font-black text-4xl sm:text-5xl text-amber-300 tracking-tight">
                  +${Math.round(annualRevenueGain).toLocaleString()}
                </div>
                <div className="text-xs text-teal-100">
                  (+${Math.round(monthlyRevenueGain).toLocaleString()} / month)
                </div>
              </div>

              {/* Metrics Breakdown List */}
              <div className="space-y-2 pt-2 text-xs border-t border-teal-500/30">
                <div className="flex justify-between text-teal-100">
                  <span>Baseline Monthly Revenue:</span>
                  <span className="font-bold">${Math.round(baselineMonthlyRevenue).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-amber-200 font-bold">
                  <span>SEOWebFly Projected Revenue:</span>
                  <span>${Math.round(projectedMonthlyRevenue).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-teal-100">
                  <span>Projected Organic Visitors:</span>
                  <span className="font-bold">{Math.round(projectedVisitors).toLocaleString()} / mo</span>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-2">
                <button
                  onClick={onOpenBookingModal}
                  className="w-full py-4 bg-white text-slate-950 hover:bg-teal-50 font-bold text-sm rounded-xl transition-all shadow-lg flex items-center justify-center gap-2 group border border-teal-400/30 cursor-pointer"
                >
                  <span>Lock In Growth Roadmap</span>
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </button>

                <button
                  onClick={handleSaveScenario}
                  disabled={isSaving}
                  className="w-full py-2.5 bg-teal-900/60 hover:bg-teal-900 text-teal-100 font-semibold text-xs rounded-xl transition-all flex items-center justify-center gap-2 border border-teal-400/20 cursor-pointer disabled:opacity-50"
                >
                  {isSaved ? (
                    <>
                      <CheckCircle className="w-3.5 h-3.5 text-amber-300" />
                      <span>Scenario Saved to Cloud Database!</span>
                    </>
                  ) : (
                    <>
                      <Cloud className="w-3.5 h-3.5 text-teal-300" />
                      <span>{isSaving ? 'Saving Scenario...' : 'Save Scenario to Firestore'}</span>
                    </>
                  )}
                </button>

                <button
                  onClick={handleExportScenarioToDrive}
                  disabled={isSavingToDrive}
                  id="export-roi-drive-btn"
                  className="w-full py-2.5 bg-[#12131A] hover:bg-[#1A1D2B] text-teal-300 hover:text-white font-semibold text-xs rounded-xl transition-all flex items-center justify-center gap-2 border border-teal-500/30 cursor-pointer disabled:opacity-50"
                >
                  {isSavingToDrive ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin text-teal-400" />
                      <span>Saving to Google Drive...</span>
                    </>
                  ) : (
                    <>
                      <HardDrive className="w-3.5 h-3.5 text-teal-400" />
                      <span>Save Scenario to Google Drive</span>
                    </>
                  )}
                </button>
              </div>

              {driveSavedMsg && (
                <div className="p-3 rounded-xl bg-teal-950/60 border border-teal-500/40 flex items-center justify-between gap-3 text-xs text-teal-200">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                    <span className="truncate">{driveSavedMsg}</span>
                  </div>
                  {driveSavedUrl && (
                    <a
                      href={driveSavedUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 font-bold text-teal-300 hover:underline shrink-0"
                    >
                      <span>View</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  )}
                </div>
              )}

              <div className="text-[11px] text-teal-200 text-center font-light italic">
                * Projections based on verified past results like 1Click Wallpapers (+608% traffic) & Inofia (+315% ROAS).
              </div>

            </div>

          </div>
        </div>

      </div>
    </section>
  );
};
